site_name: Aviation Model
theme:
  name: "material"

nav:
  - Home: "index.md"
  - Aviation model: "aviation.md"
  - Course notes: "course_notes.md"
  - API Documentation:
      - Aviation: "api/index.md"
      - Fleet: "api/fleet.md"

plugins:
  - mkdocstrings
  - search
  - bibtex:
      bib_file: "https://api.zotero.org/users/6401108/collections/DXT8EFTF/items?format=bibtex"

markdown_extensions:
  - footnotes
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
