[project]
name = "aviation"
version = "0.1.0"
description = "Sample aviation project to learn about uv, git, and aia code database"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
docs = [
    "mkdocs>=1.6.1",
]
